CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE company (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(255) NOT NULL,
    CONSTRAINT "PK_company" PRIMARY KEY ("Id")
);

CREATE TABLE account (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "Code" character varying(50) NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Type" character varying(50) NOT NULL,
    CONSTRAINT "PK_account" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_account_company_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES company ("Id") ON DELETE CASCADE
);

CREATE TABLE transaction (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CompanyId" integer NOT NULL,
    "TransactionNo" integer NOT NULL,
    "Date" timestamp with time zone NOT NULL,
    "Description" character varying(500),
    CONSTRAINT "PK_transaction" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_transaction_company_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES company ("Id") ON DELETE CASCADE
);

CREATE TABLE transaction_item (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TransactionId" integer NOT NULL,
    "AccountId" integer NOT NULL,
    "LineDescription" character varying(500),
    debit numeric(18,2) NOT NULL,
    credit numeric(18,2) NOT NULL,
    CONSTRAINT "PK_transaction_item" PRIMARY KEY ("Id"),
    CONSTRAINT ck_entry_nonneg CHECK ((debit >= 0 AND credit >= 0)),
    CONSTRAINT ck_entry_one_side CHECK (((debit = 0 AND credit > 0) OR (credit = 0 AND debit > 0))),
    CONSTRAINT "FK_transaction_item_account_AccountId" FOREIGN KEY ("AccountId") REFERENCES account ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_transaction_item_transaction_TransactionId" FOREIGN KEY ("TransactionId") REFERENCES transaction ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_account_CompanyId_Code" ON account ("CompanyId", "Code");

CREATE UNIQUE INDEX "IX_company_Name" ON company ("Name");

CREATE UNIQUE INDEX "IX_transaction_CompanyId_TransactionNo" ON transaction ("CompanyId", "TransactionNo");

CREATE INDEX "IX_transaction_item_AccountId" ON transaction_item ("AccountId");

CREATE INDEX "IX_transaction_item_TransactionId" ON transaction_item ("TransactionId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250822081800_Init', '10.0.2');

COMMIT;

START TRANSACTION;
ALTER TABLE transaction_item DROP CONSTRAINT "FK_transaction_item_account_AccountId";

ALTER TABLE transaction_item DROP CONSTRAINT "FK_transaction_item_transaction_TransactionId";

DROP INDEX "IX_transaction_item_AccountId";

DROP INDEX "IX_transaction_item_TransactionId";

ALTER TABLE transaction_item RENAME COLUMN "TransactionId" TO transaction_no;

ALTER TABLE transaction_item RENAME COLUMN "AccountId" TO company_id;

ALTER TABLE transaction_item ADD account_code character varying(50) NOT NULL DEFAULT '';

ALTER TABLE transaction ADD CONSTRAINT "AK_transaction_CompanyId_TransactionNo" UNIQUE ("CompanyId", "TransactionNo");

ALTER TABLE account ADD CONSTRAINT "AK_account_CompanyId_Code" UNIQUE ("CompanyId", "Code");

CREATE INDEX "IX_transaction_item_company_id_account_code" ON transaction_item (company_id, account_code);

CREATE INDEX "IX_transaction_item_company_id_transaction_no" ON transaction_item (company_id, transaction_no);

ALTER TABLE transaction_item ADD CONSTRAINT "FK_transaction_item_account_company_id_account_code" FOREIGN KEY (company_id, account_code) REFERENCES account ("CompanyId", "Code") ON DELETE RESTRICT;

ALTER TABLE transaction_item ADD CONSTRAINT "FK_transaction_item_transaction_company_id_transaction_no" FOREIGN KEY (company_id, transaction_no) REFERENCES transaction ("CompanyId", "TransactionNo") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250822091627_CompositeKeys', '10.0.2');

COMMIT;

START TRANSACTION;
CREATE TABLE "AppLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TsUtc" timestamp with time zone NOT NULL,
    "CompanyId" integer,
    "SourceFile" text NOT NULL,
    "SourceFunction" text NOT NULL,
    "EventType" text NOT NULL,
    "Level" text NOT NULL,
    "LogCode" text NOT NULL,
    "LogMessage" text NOT NULL,
    CONSTRAINT "PK_AppLogs" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250926133053_AppLog', '10.0.2');

COMMIT;

START TRANSACTION;
CREATE TABLE app_user (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(255) NOT NULL,
    "PasswordHash" text NOT NULL,
    "IsAdmin" boolean NOT NULL,
    "CreatedAtUtc" timestamp with time zone NOT NULL,
    "LastLoginAtUtc" timestamp with time zone,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_app_user" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_app_user_Email" ON app_user ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251125154425_AddAppUsers', '10.0.2');

COMMIT;

START TRANSACTION;
ALTER TABLE transaction_item DROP CONSTRAINT ck_entry_one_side;

ALTER TABLE transaction_item ADD CONSTRAINT ck_entry_one_side CHECK (((debit = 0 AND credit >= 0) OR (credit = 0 AND debit >= 0)));

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260226155718_AllowZeroZeroTransactionItem', '10.0.2');

COMMIT;

START TRANSACTION;
CREATE TABLE account_type_prefix (
    "Prefix" character varying(10) NOT NULL,
    "AccountType" character varying(50) NOT NULL,
    CONSTRAINT "PK_account_type_prefix" PRIMARY KEY ("Prefix")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260331060117_AddAccountTypePrefix', '10.0.2');

COMMIT;

